export const SIDEBAR = [
    {
        sysMenuId: 1,
        parentId: null,
        code: "HOME",
        name: "Tổng quan",
        to: "/admin/dashboard",
        sortOrder: 1,
        path: "/1/",
        isActive: 1,
        label: "Tổng quan",
        value: "/admin/dashboard",
        icon: "pi pi-th-large",
    },
    {
        sysMenuId: 2,
        parentId: null,
        code: "MANAGE_ORDER",
        name: "Đơn hàng",
        sortOrder: 2,
        path: "/2/",
        isActive: 1,
        label: "Đơn hàng",
        value: "",
        icon: "bx bx-receipt"
    },
    {
        sysMenuId: 3,
        parentId: 2,
        code: "ORDER_DELIVERY",
        name: "Tạo đơn và giao hàng",
        to: "/admin/orders/create",
        sortOrder: 3,
        path: "/2/3/",
        isActive: 1,
        label: "Tạo đơn và giao hàng",
        value: "/admin/orders/create",
        icon: "pi pi-inbox",
    },
    {
        sysMenuId: 4,
        parentId: 2,
        code: "ORDER_LIST",
        name: "Danh sách đơn hàng",
        to: "/admin/orders",
        sortOrder: 2,
        path: "/2/4/",
        isActive: 1,
        label: "Danh sách đơn hàng",
        value: "/admin/orders",
        icon: "pi pi-shopping-cart"
    },
    {
        sysMenuId: 5,
        parentId: 2,
        code: "EXCHANGE",
        name: "Đổi trả",
        to: "/admin/order-returns",
        sortOrder: 2,
        path: "/2/5/",
        isActive: 1,
        label: "Đổi trả",
        value: "/admin/order-returns",
        icon: "pi pi-wallet"
    },
    {
        sysMenuId: 6,
        parentId: null,
        code: "TRANSPORT",
        name: "Vận chuyển",
        sortOrder: 1,
        path: "/6/",
        isActive: 1,
        label: "Vận chuyển",
        value: "",
        icon: "bx bx-paper-plane" // bx bx-transfer
    },
    {
        sysMenuId: 9,
        parentId: 6,
        code: "TRANSPORT_COD_FEE",
        name: "Tổng quát",
        to: "/admin/transport-code-fee",
        sortOrder: 1,
        path: "/6/9/",
        isActive: 1,
        label: "Tổng quát",
        value: "/admin/transport-code-fee",
        icon: "bx bx-line-chart"
    },
    {
        sysMenuId: 7,
        parentId: 6,
        code: "MANAGE_TRANSPORT",
        name: "Quản lý giao hàng",
        to: "/admin/delivery_management_list",
        sortOrder: 1,
        path: "/6/7/",
        isActive: 1,
        label: "Quản lý giao hàng",
        value: "/admin/delivery_management_list",
        icon: "bx bx-task"
    },
    {
        sysMenuId: 8,
        parentId: 6,
        code: "COD_FEE",
        name: "Đối soát COD & phí",
        to: "/admin/cod-fee",
        sortOrder: 1,
        path: "/6/8/",
        isActive: 1,
        label: "Đối soát COD & phí",
        value: "/admin/cod-fee",
        icon: "bx bx-barcode-reader"
    },
    {
        sysMenuId: 10,
        parentId: null,
        code: "PRODUCTS",
        name: "Sản phẩm",
        sortOrder: 1,
        path: "/10/",
        isActive: 1,
        label: "Sản phẩm",
        value: "",
        icon: "bx bx-cube-alt"
    },
    {
        sysMenuId: 11,
        parentId: 10,
        code: "MANAGE_CATEGORY",
        name: "Danh mục sản phẩm",
        to: "/admin/category",
        sortOrder: 1,
        path: "/10/11/",
        isActive: 1,
        label: "Danh mục sản phẩm",
        value: "/admin/products",
        icon: "bx bx-category"
    },
    {
        sysMenuId: 12,
        parentId: 10,
        code: "MANAGE_PRODUCT",
        name: "Quản lý sản phẩm",
        to: "/admin/products",
        sortOrder: 1,
        path: "/10/12/",
        isActive: 1,
        label: "Quản lý sản phẩm",
        icon: "bx bx-cube-alt"
    },
    {
        sysMenuId: 17,
        parentId: 10,
        code: "MANAGE_WAREHOUSE",
        name: "Quản lý kho",
        to: "/admin/ware-house",
        sortOrder: 1,
        path: "/10/17/",
        isActive: 1,
        label: "Quản lý kho",
        value: "/admin/ware-house",
        icon: "bx bx-building-house"
    },
    {
        sysMenuId: 13,
        parentId: null,
        code: "MANAGE_CONFIG",
        name: "Cấu hình",
        sortOrder: 1,
        path: "/13/",
        isActive: 1,
        label: "Cấu hình",
        icon: "bx bx-cog",
    },
    {
        sysMenuId: 14,
        parentId: 13,
        code: "MANAGE_CONFIG_PRODUCT",
        name: "Sản phẩm",
        sortOrder: 1,
        path: "/13/14/",
        isActive: 1,
        label: "Sản phẩm",
        icon: "bx bx-cube-alt"
    },
    {
        sysMenuId: 15,
        parentId: 14,
        code: "MANAGE_CONFIG_PRODUCT_COLOR",
        name: "Màu sắc",
        to: "/admin/config/product-color",
        sortOrder: 1,
        path: "/13/14/15/",
        isActive: 1,
        label: "Màu sắc",
        icon: "bx bx-cookie"
    },
    {
        sysMenuId: 16,
        parentId: 14,
        code: "MANAGE_CONFIG_PRODUCT_SIZE",
        name: "Kích cỡ",
        to: "/admin/config/product-size",
        sortOrder: 1,
        path: "/13/14/16/",
        isActive: 1,
        label: "Kích cỡ",
        icon: "bx bx-closet"
    }
]
export const ICON_MENU = {
    'HOME': 'pi pi-home',
    'MANAGE': 'pi pi-fw pi-shield',
    'manage-soft': 'pi pi-fw pi-cog',
    'manage-system': 'pi pi-fw pi-sitemap',
    'report': 'pi pi-chart-line',
}