import { STATUS_ORDER } from "../enums";

export const GHN_TOKEN = 'c26fbc83-124e-11ed-b136-06951b6b7f89'
export const SHOP_ID = 117267
export const MAP_TAB_VIEW = {
    0: STATUS_ORDER.WAITING_PAYMENT,
    1: STATUS_ORDER.ORDER,
    2: STATUS_ORDER.APPROVE_ORDER,
    3: STATUS_ORDER.PACK_ORDER,
    4: STATUS_ORDER.DELIVERING,
    5: STATUS_ORDER.COMPLETE_ORDER,
    6: STATUS_ORDER.CANCEL_ORDER
};
// export const BANK_NAME =